"""Tiny 1D U-Net audio fixer.

Maps Mimi-round-tripped audio → original audio. Trained on pairs
generated by scripts/19_prepare_fixer_data.py.

Design choices and what they buy us:

* **1D U-Net over raw waveform**. The simplest end-to-end audio architecture
  that has the inductive bias of multi-scale processing. The bottleneck sees
  long-range context (after 3 downsamples by 2x, one bottleneck position
  covers 8 input samples × kernel-5 receptive field).
* **Residual output**. The network's final layer adds to the input rather
  than replacing it. This means at init the network is approximately the
  identity — the worst it can do is leave the audio alone — and training
  only has to learn the correction. Standard trick from image super-res
  (Kim et al. "Accurate Image Super-Resolution Using Very Deep CNNs").
* **GroupNorm rather than BatchNorm**. Batch=8-16 is small, BatchNorm stats
  are noisy, GroupNorm is per-sample and doesn't suffer.
* **GELU activations**. Smooth, behaves well at small init, what every
  modern transformer uses.
* **No dilations / no transformer**. The receptive field after 3 downsamples
  is ~hundreds of samples; that's enough for codec-artifact denoising.
  Add dilations or a transformer bottleneck only if quality is short.
"""
from __future__ import annotations

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F


@dataclass
class FixerConfig:
    channels: tuple[int, ...] = (32, 64, 128, 128)  # widths at each U-Net depth
    kernel_size: int = 5
    groups: int = 8                                  # for GroupNorm
    # The receptive field grows ~kernel * sum(strides) per depth; with k=5
    # and 3 stride-2 downsamples it's ~hundreds of samples at the input.


class ConvBlock(nn.Module):
    """Conv1d → GroupNorm → GELU. Padding keeps the temporal dimension fixed
    (we change resolution only via explicit strided conv / transpose conv)."""

    def __init__(self, in_c: int, out_c: int, k: int, groups: int, stride: int = 1):
        super().__init__()
        self.conv = nn.Conv1d(in_c, out_c, kernel_size=k, stride=stride,
                              padding=(k - 1) // 2)
        self.norm = nn.GroupNorm(min(groups, out_c), out_c)
        self.act = nn.GELU()

    def forward(self, x):
        return self.act(self.norm(self.conv(x)))


class UpBlock(nn.Module):
    """Transpose-conv upsample by 2 → concat skip → ConvBlock fuses them."""

    def __init__(self, in_c: int, out_c: int, skip_c: int, k: int, groups: int):
        super().__init__()
        self.up = nn.ConvTranspose1d(in_c, out_c, kernel_size=4, stride=2, padding=1)
        self.fuse = ConvBlock(out_c + skip_c, out_c, k, groups)

    def forward(self, x, skip):
        x = self.up(x)
        # If transpose conv produced one-off length difference vs skip, trim.
        if x.shape[-1] != skip.shape[-1]:
            t = min(x.shape[-1], skip.shape[-1])
            x = x[..., :t]
            skip = skip[..., :t]
        x = torch.cat([x, skip], dim=1)
        return self.fuse(x)


class FixerUNet(nn.Module):
    """Waveform → waveform residual U-Net."""

    def __init__(self, cfg: FixerConfig):
        super().__init__()
        self.cfg = cfg
        c = cfg.channels
        k = cfg.kernel_size
        g = cfg.groups

        # Input stem keeps T unchanged, lifts to first channel count.
        self.stem = ConvBlock(1, c[0], k, g)

        # Encoder: each step halves T via stride-2 conv.
        self.down = nn.ModuleList()
        for i in range(len(c) - 1):
            self.down.append(nn.ModuleList([
                ConvBlock(c[i], c[i], k, g),           # process at this scale
                ConvBlock(c[i], c[i+1], k, g, stride=2),  # downsample 2x
            ]))

        # Bottleneck: a couple of conv blocks at the smallest scale.
        self.bottleneck = nn.Sequential(
            ConvBlock(c[-1], c[-1], k, g),
            ConvBlock(c[-1], c[-1], k, g),
        )

        # Decoder: mirror of encoder, with skip concat.
        self.up = nn.ModuleList()
        for i in reversed(range(len(c) - 1)):
            self.up.append(UpBlock(c[i+1], c[i], c[i], k, g))

        # Output head: produce a single-channel waveform-residual.
        self.out = nn.Conv1d(c[0], 1, kernel_size=k, padding=(k - 1) // 2)

        # Init the output head near-zero so we start as near-identity.
        nn.init.zeros_(self.out.weight)
        nn.init.zeros_(self.out.bias)

    def num_parameters(self) -> int:
        return sum(p.numel() for p in self.parameters())

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """x: (B, 1, T) waveform. Returns (B, 1, T) cleaned waveform."""
        h = self.stem(x)
        skips = []
        for proc, down in self.down:
            h = proc(h)
            skips.append(h)
            h = down(h)
        h = self.bottleneck(h)
        for up_block, skip in zip(self.up, reversed(skips)):
            h = up_block(h, skip)
        delta = self.out(h)
        # Match length defensively (any 1-sample skew from up/down rounding).
        T = min(delta.shape[-1], x.shape[-1])
        return x[..., :T] + delta[..., :T]


# ---------------------------------------------------------------------------------------
# Loss helpers

def _stft_mag(x: torch.Tensor, n_fft: int, hop: int) -> torch.Tensor:
    """Compute magnitude STFT. x: (B, 1, T) -> (B, F, T_frames)."""
    win = torch.hann_window(n_fft, device=x.device)
    s = torch.stft(x.squeeze(1), n_fft=n_fft, hop_length=hop, window=win,
                   return_complex=True, center=True)
    return s.abs()


def multi_scale_spectral_loss(
    pred: torch.Tensor, target: torch.Tensor,
    scales=((512, 128), (1024, 256), (2048, 512)),
) -> torch.Tensor:
    """L1 in log-magnitude STFT across multiple FFT sizes. Vocoder-standard
    perceptual loss; matches what the ear cares about across multiple scales."""
    loss = 0.0
    for n_fft, hop in scales:
        a = _stft_mag(pred, n_fft, hop).clamp_min(1e-7).log()
        b = _stft_mag(target, n_fft, hop).clamp_min(1e-7).log()
        loss = loss + F.l1_loss(a, b)
    return loss / len(scales)


def fixer_loss(pred: torch.Tensor, target: torch.Tensor,
               spectral_weight: float = 1.0) -> tuple[torch.Tensor, dict]:
    """Combined waveform-L1 + multi-scale log-mag spectral L1."""
    wav = F.l1_loss(pred, target)
    spec = multi_scale_spectral_loss(pred, target)
    total = wav + spectral_weight * spec
    return total, {"wav": float(wav), "spec": float(spec), "total": float(total)}
